apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::646071784763:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-13VGTJXB4002C
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::646071784763:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-01-27T13:58:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1671"
  uid: e5420527-0e38-4094-bd31-109bfc6be593
